language: node_js
cache: yarn
dist: trusty
node_js:
  - 8
jobs:
  include:
    - stage: mysql
      services:
        - mysql
      addons:
        apt:
          sources:
            - mysql-5.7-trusty
          packages:
            - mysql-server
            - mysql-client
      before_install:
        - mysql -e 'CREATE DATABASE IF NOT EXISTS withmoney_test;'
        - mysql -e "use mysql; update user set authentication_string=PASSWORD('123') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
        - service mysql restart
        - cp .env.example .env
      before_script:
        - yarn run config:db
        - yarn run pretest
        - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
        - "chmod +x ./cc-test-reporter"
        - "./cc-test-reporter before-build"
      after_script:
        - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
    - stage: postgres
      services:
        - postgresql
      before_script:
        - psql -c 'create database withmoney_test;' -U postgres
        - cp .env.example .env
        - yarn run config:db
        - sed -i 's/mysql/postgres/g' config/database.json
        - sed -i 's/root/postgres/g' config/database.json
        - sed -i 's/123//g' config/database.json
        - yarn run pretest
